networks:
  traefik-proxy:
    external: true

services:
  todo_api:
    build:
      context: .
      dockerfile: Dockerfile
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
       - "8000:8000"
    env_file:
      - ./.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.todo.rule=Host(`todo.dev.${USER}.merit.edu`)"
    networks:
      - traefik-proxy
