# Generated by Django 5.1.1 on 2024-09-17 00:00

import random
from django.db import migrations


def create_random_todos(apps, schema_editor):
    Todo = apps.get_model('todo', 'Todo')
    titles = [
        'Buy groceries', 'Read a book', 'Write code', 'Go for a run', 'Call mom',
        'Clean the house', 'Pay bills', 'Watch a movie', 'Plan a trip', 'Cook dinner',
        'Attend meeting', 'Fix the bike'
    ]
    contents = [
        'Remember to buy milk and eggs', 'Finish reading the novel', 'Complete the project',
        'Run 5 kilometers', 'Catch up with mom', 'Vacuum and dust the living room',
        'Pay electricity and water bills', 'Watch the latest release', 'Plan the itinerary',
        'Prepare a healthy meal', 'Discuss project updates', 'Repair the flat tire'
    ]
    todos = [
        Todo(title=title, content=content, completed=random.choice([True, False]))
        for title, content in zip(titles, contents)
    ]
    Todo.objects.bulk_create(todos)


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_random_todos),
    ]
