# Generated by Django 5.1.1 on 2025-05-14 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_add_random_todos'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'managed': True, 'ordering': ['-created_at'], 'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='createdAt',
            new_name='created_at',
        ),
    ]
